
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: acer
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

bezkoder:
  app:
    jwtSecret:  bezKoderSecretKey
    jwtExpirationMs:  86400000
    jwtCookieName:  bezkoder